"""
evaluate_scalability.py

Evaluates the trained SLIM MARL policies for N=4, 6, 8, 10 agents
to verify the network effect (increased P2P volume per agent at larger scales).

Usage:
    python evaluate_scalability.py

Requires models in `models_scalability/` generated by `train_scalability.py`.
"""

import os
import sys
import numpy as np
import pandas as pd
from stable_baselines3 import PPO

# Ensure project root is on path
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from train.energy_env_robust import EnergyMarketEnvRobust
from train.autonomous_guard import AutonomousGuard

def evaluate_scale(n_agents: int, model_path: str, eval_steps: int = 1000):
    if not os.path.exists(model_path + ".zip"):
        print(f"[{n_agents} Agents] SKIPPED: Model not found at {model_path}.zip")
        return None

    # Use deterministic evaluation
    env = EnergyMarketEnvRobust(n_agents=n_agents, random_start_day=False)
    model = PPO.load(model_path, env=env)
    
    # Optional: We can use the AutonomousGuard if we want standard 3-layer bounds
    guard = AutonomousGuard(n_agents=n_agents)

    obs, _ = env.reset(seed=123)
    
    total_p2p = 0.0
    total_profit = 0.0
    
    for _ in range(eval_steps):
        # 1. Predict raw action deterministically
        raw_action, _ = model.predict(obs, deterministic=True)
        
        # 2. Apply projection bounds (optional but recommended for consistency)
        state_info = env.get_state() if hasattr(env, "get_state") else None
        safe_action = raw_action
        if state_info:
            safe_action, _ = guard.guard_action(raw_action, state_info)
            
        # 3. Step env
        obs, reward, terminated, truncated, infos = env.step(safe_action)
        
        if "p2p_volume" in infos:
            total_p2p += infos["p2p_volume"]
            
        if "profit_breakdown" in infos:
            total_profit += infos["profit_breakdown"].get("net_reward", sum(reward))
        elif "absolute_profit_usd" in infos:
            total_profit += infos["absolute_profit_usd"]
        else:
            total_profit += sum(reward)
            
        if terminated or truncated:
            obs, _ = env.reset()

    env.close()

    # Per-agent metrics
    p2p_per_agent = total_p2p / n_agents
    profit_per_agent = total_profit / n_agents
    
    return {
        "N": n_agents,
        "Total P2P (kWh)": total_p2p,
        "P2P / Agent (kWh)": p2p_per_agent,
        "Total Profit ($)": total_profit,
        "Profit / Agent ($)": profit_per_agent
    }

def main():
    print("===========================================")
    print("EVALUATING SCALABILITY NETWORK EFFECTS")
    print("===========================================")
    
    # Try multiple common directories if user named them differently
    search_dirs = ["models_scalability", "research_q1/models/slim_ppo_N", "models_phase5_hybrid"]
    
    scales = [4, 6, 8, 10]
    results = []
    
    for n in scales:
        # Resolve model path
        model_path = f"models_scalability/ppo_N{n}"
        if not os.path.exists(model_path + ".zip"):
             # Fallback check
             fallback = f"research_q1/models/slim_ppo_N{n}/slim_ppo_N{n}_100000_steps"
             if os.path.exists(fallback + ".zip"):
                 model_path = fallback
                 
        res = evaluate_scale(n, model_path, eval_steps=1000)
        if res:
            results.append(res)
            
    if not results:
        print("\nNo models found. Please run `python train_scalability.py` first.")
        return
        
    df = pd.DataFrame(results)
    
    print("\n--- PERFORMANCE SUMMARY (1000 evaluation steps) ---\n")
    print(df.to_markdown(index=False, floatfmt=".2f"))
    print("\nObservation:")
    print("As N increases, P2P / Agent should increase due to positive network effects")
    print("and higher probability of finding complementary trading partners.")

if __name__ == "__main__":
    main()
